apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy
  labels:
    app: energy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: energy
  template:
    metadata:
      labels:
        app: energy
    spec:
      containers:
      - name: shop
        image: oosemicro/energy:0.0.1
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP