communication: 
  hello: moin

server:
  port: ${PORT:8200}
  
info:
  energy: ok
  creator: Dipl.-Ing Hermann Woock
  date: 05.03.2020
  systems: warp kernel
  

spring:
  application:
    name: energy-support  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:      trusted:      - de.woock.entity
      - java.util
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: 
        - "*" 
        - hystrix.stream
      base-path: /actuator
  endpoint:
    health:
      show-details: always  
      
logging:
  level:
    root: error
    de.woock: debug
    org.springframework.cloud: debug